use tcc_nbb;

-- MySQL Script generated by MySQL Workbench
-- Thu May  9 17:31:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc_nbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc_nbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc_nbb` DEFAULT CHARACTER SET utf8 ;
USE `tcc_nbb` ;

-- -----------------------------------------------------
-- Table `tcc_nbb`.`temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_nbb`.`temporada` (
  `ano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_nbb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_nbb`.`equipe` (
  `equipe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_nbb`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_nbb`.`jogos` (
  `id` INT NOT NULL,
  `placar_casa` INT NULL,
  `placar_visitante` INT NULL,
  `data` DATETIME NULL,
  `round` INT NULL,
  `stage` INT NULL,
  `ano` VARCHAR(45) NOT NULL,
  `equipe_casa` VARCHAR(45) NOT NULL,
  `equipe_visitante` VARCHAR(45) NOT NULL,
  `casa_pts` DECIMAL NULL,
  `casa_3p` DECIMAL NULL,
  `casa_2p` DECIMAL NULL,
  `casa_ll` DECIMAL NULL,
  `casa_rt` DECIMAL NULL,
  `casa_ro` DECIMAL NULL,
  `casa_rd` DECIMAL NULL,
  `casa_as` DECIMAL NULL,
  `casa_er` DECIMAL NULL,
  `casa_ia_perc` DECIMAL NULL,
  `casa_3pc` DECIMAL NULL,
  `casa_3pt` DECIMAL NULL,
  `casa_3p_perc` DECIMAL NULL,
  `casa_2pc` DECIMAL NULL,
  `casa_2pt` DECIMAL NULL,
  `casa_2p_perc` DECIMAL NULL,
  `casa_llc` DECIMAL NULL,
  `casa_llt` DECIMAL NULL,
  `casa_ll_perc` DECIMAL NULL,
  `casa_en` DECIMAL NULL,
  `casa_br` DECIMAL NULL,
  `casa_be` DECIMAL NULL,
  `casa_to` DECIMAL NULL,
  `casa_fc` DECIMAL NULL,
  `casa_tfc` DECIMAL NULL,
  `casa_et` DECIMAL NULL,
  `casa_vi` DECIMAL NULL,
  `visitante_be` DECIMAL NULL,
  `casa_ef` DECIMAL NULL,
  `visitante_pts` DECIMAL NULL,
  `visitante_3p` DECIMAL NULL,
  `visitante_2p` DECIMAL NULL,
  `visitante_rt` DECIMAL NULL,
  `visitante_ro` DECIMAL NULL,
  `visitante_rd` DECIMAL NULL,
  `visitante_as` DECIMAL NULL,
  `visitante_er` DECIMAL NULL,
  `visitante_ia_perc` DECIMAL NULL,
  `visitante_3pc` DECIMAL NULL,
  `visitante_3pt` DECIMAL NULL,
  `visitante_3p_perc` DECIMAL NULL,
  `visitante_2pc` DECIMAL NULL,
  `visitante_2pt` DECIMAL NULL,
  `visitante_2p_perc` DECIMAL NULL,
  `visitante_llc` DECIMAL NULL,
  `visitante_llt` DECIMAL NULL,
  `visitante_ll` DECIMAL NULL,
  `visitante_en` DECIMAL NULL,
  `visitante_br` DECIMAL NULL,
  `visitante_to` DECIMAL NULL,
  `visitante_fc` DECIMAL NULL,
  `visitante_tfc` DECIMAL NULL,
  `visitante_et` DECIMAL NULL,
  `visitante_vi` DECIMAL NULL,
  `visitante_ef` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jogos_temporada_idx` (`ano` ASC),
  INDEX `fk_jogos_equipe1_idx` (`equipe_casa` ASC),
  INDEX `fk_jogos_equipe2_idx` (`equipe_visitante` ASC),
  CONSTRAINT `fk_jogos_temporada`
    FOREIGN KEY (`ano`)
    REFERENCES `tcc_nbb`.`temporada` (`ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_equipe1`
    FOREIGN KEY (`equipe_casa`)
    REFERENCES `tcc_nbb`.`equipe` (`equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_equipe2`
    FOREIGN KEY (`equipe_visitante`)
    REFERENCES `tcc_nbb`.`equipe` (`equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
